apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluation
metadata:
  name: semantic-agent-performance-evaluator
  namespace: default
spec:
  description: "Evaluates agent execution and performance using semantic expressions"
  type: event
  config:
    rules:
      - name: "agent_executed"
        expression: "agent.was_executed()"
        description: "Verifies that an agent was executed"
        weight: 1
      
      - name: "agent_success"
        expression: "agent.get_success_rate() >= 0.9"
        description: "Ensures agent success rate is above 90%"
        weight: 3
      
      - name: "specific_agent"
        expression: "agents.was_executed('researcher', scope='current')"
        description: "Verifies researcher agent was executed"
        weight: 1
      
      - name: "agent_tools_used"
        expression: "agents.get_tools_used('researcher').length >= 2"
        description: "Checks if researcher used at least 2 tools"
        weight: 2
      
      - name: "agent_execution_count"
        expression: "agent.get_execution_count() <= 5"
        description: "Ensures no excessive agent re-executions"
        weight: 1