replicaCount: 1

image:
  repository: filesystem-mcp-server
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

env:
  PORT: "8080"
  BASE_DATA_DIR: "/data"
  SESSION_FILE: "/data/sessions/sessions.json"
  MAX_SESSIONS: "1000"

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi
    ephemeral-storage: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  name: mcp-filesystem-sa
  create: true