# Service account token for argo workflow
# Required for Kubernetes 1.24+ where tokens are not auto-created
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflow.service-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: argo-workflow
  labels:
    app.kubernetes.io/name: argo-workflow
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: service-account-token
type: kubernetes.io/service-account-token
