apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "mcp-filesystem.fullname" . }}
automountServiceAccountToken: false