{{- if .Values.otelEnvironmentVariableSecrets.enabled }}
{{- $endpoint := printf "http://%s.%s.svc.cluster.local:%v" .Values.service.name .Values.namespace (.Values.service.port | int) }}
{{- range .Values.otelEnvironmentVariableSecrets.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: otel-environment-variables
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
stringData:
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ $endpoint }}
  OTEL_EXPORTER_OTLP_HEADERS: ""
{{- end }}
{{- end }}
